namespace TAS_Project.Database
{
    public class SaveInputTypeData : ISaveInputTypeData
    {
        public void AddAnInputType(InputType value){ //Method for adding an individual Input Type
            string cs;
            try
            {
                cs =@"URI=file:C:\Users\hnnhp\source\repos\MIS 321\pa4-hdpetty-1\API\Models\posts.db";//NEEDS TO BE UPDATED
            }
            catch (FileNotFoundException e) //Error Check
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("Something went wrong.....input type was not added. {0}", e);
                Console.ForegroundColor = ConsoleColor.White;
                return;
            }
            using var con= new SQLiteConnection(cs); 
            con.Open(); //opens a connection to the database

            using var cmd= new SQLiteCommand(con);
            
            cmd.CommandText=@"INSERT INTO InputType(InputTypeName) VALUES(@InputTypeName)"; //Adds new input type into the database. Id # is autogenerated
            cmd.Parameters.AddWithValue("@InputTypeName", value.InputTypeName);
            cmd.Prepare();
            cmd.ExecuteNonQuery();
        }
    }
}