using System.Data.SQLite;
using System;
using System.IO;
using TAS_Project.Interfaces;

namespace TAS_Project.Models
{
    public class SaveInputChoicesData : ISaveInputChoicesData
    {
        public void UpdateInputChoice(InputChoices value){
            string cs;
            try
            {
                cs=@"URI=file:C:\Users\hnnhp\source\repos\MIS 321\TAS-Project\API\Database\TAS.db";
            }
            catch (FileNotFoundException e) //Error Check
            {
                Console.ForegroundColor = ConsoleColor.Red;
                Console.WriteLine("Something went wrong.....input choice was not added. {0}", e);
                Console.ForegroundColor = ConsoleColor.White;
                return;
            }
            using var con= new SQLiteConnection(cs); 
            con.Open(); //opens a connection to the database

            using var cmd= new SQLiteCommand(con);
            
            cmd.CommandText=@"INSERT INTO InputChoices(InputChoiceName, InputTypeId) VALUES(@InputChoiceName, @InputTypeId)"; //Adds new input choice into the database. Id # is autogenerated
            cmd.Parameters.AddWithValue("@InputChoiceName", value.InputChoiceName);
            cmd.Parameters.AddWithValue("@InputTypeId", value.InputTypeId);
            cmd.Prepare();
            cmd.ExecuteNonQuery();
        }
    }
}